name: Log Events

on:
  create:
  delete:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name for Create, Delete, Push
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.ref.substring('refs/heads/'.length);
            console.log('branchName', branchName);
