name: Deploy an environment when a pull request is opened or 
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize, labeled, unlabeled ]

    
jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
